### ISSUE TITLE
More detail for evaluation.

### ISSUE THREAD

**Issue by xumingyu2021** [microsoft/MMLU-CF#3]
"Step 1. Validation set evaluation: Obtaining the validation results for your model using LLM evaluation tools, [OpenCompass](https://github.com/open-compass/opencompass). The validation dataset download from [🤗 Huggingface](https://huggingface.co/datasets/microsoft/MMLU-CF). The data directory structure in the opencompass:"

Where should I put the downloaded file? And what command line should be used to run the evaluation program? It would be better if you could provide a more detailed explanation of this. 

Thank you！

**Comment by fistyee** [comment]
Please place the <val> and <dev> files under opencompass/data/mmlu_cf. The MMLU-CF validation branch of OpenCompass is currently pending merge. Please wait for it to be finalized.

**Comment by huangyangyu** [comment]
> "Step 1. Validation set evaluation: Obtaining the validation results for your model using LLM evaluation tools, [OpenCompass](https://github.com/open-compass/opencompass). The validation dataset download from [🤗 Huggingface](https://huggingface.co/datasets/microsoft/MMLU-CF). The data directory structure in the opencompass:"
> 
> Where should I put the downloaded file? And what command line should be used to run the evaluation program? It would be better if you could provide a more detailed explanation of this.
> 
> Thank you！

Hi Mingyu, the official OpenCompass repo has already supported the evaluation of MMLU-CF.

**Comment by xumingyu2021** [comment]
Thank you!
